/* 동기화 이력 관리 */
CREATE TABLE COMTNBBSMANAGE
(
	SYNC_ID					CHAR(20) NOT NULL,
	NTT_ID					NUMBER(20) NOT NULL,
	BBS_ID               	CHAR(40) NOT NULL,
	SYNC_STTUS_CODE 		CHAR(1) NULL,
	REGIST_PNTTM 			DATE NULL,
	SYNC_PNTTM 				DATE NULL,
	ERROR_PNTTM 			DATE NULL,
	CONSTRAINT  COMTNBBSMANAGE_PK PRIMARY KEY (SYNC_ID)
)
;