/* 동기화 이력 로그 */
CREATE TABLE COMTNBBSSYNCLOG
(
	SYNC_ID 				CHAR(20) NOT NULL,
	NTT_ID					NUMERIC(20) NOT NULL,
	BBS_ID               	CHAR(40) NOT NULL,
	SYNC_STTUS_CODE 		CHAR(1) NULL,
	REGIST_PNTTM 			TIMESTAMP NULL,
	SYNC_PNTTM 				TIMESTAMP NULL,
	ERROR_PNTTM 			TIMESTAMP NULL,
	 PRIMARY KEY (SYNC_ID)
)
;