---
version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: bbs_rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - bbs_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
    name: bbs_rabbitmq_data

networks:
  bbs_network:
    name: bbs_network
    driver: bridge
